### ISSUE TITLE
default feature "async" with "async-tokio" causes conflicts without disabling the default features

### ISSUE THREAD

**Issue by brahmlower** [jedisct1/rust-dnsclient#9]
Hey @jedisct1! 👋 I encountered a compilation error while building this lib with the "async-tokio" feature enabled.

```
   Compiling dnsclient v0.1.17 (/Users/brahmlower/development/rust-dnsclient)
error[E0252]: the name `AsyncBackend` is defined multiple times
  --> src/async.rs:13:5
   |
10 | use crate::backend::async_std::AsyncBackend;
   |     --------------------------------------- previous import of the type `AsyncBackend` here
...
13 | use crate::backend::async_tokio::AsyncBackend;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `AsyncBackend` reimported here
   |
   = note: `AsyncBackend` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
   |
13 | use crate::backend::async_tokio::AsyncBackend as OtherAsyncBackend;
   |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: unused import: `crate::backend::async_tokio::AsyncBackend`
  --> src/async.rs:13:5
   |
13 | use crate::backend::async_tokio::AsyncBackend;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0252`.
warning: `dnsclient` (lib) generated 1 warning
error: could not compile `dnsclient` due to previous error; 1 warning emitted
```

After some digging, I realized that this library has the "async" feature included in its list of default features, so when I added the "async-tokio" feature, I was actually trying to compile with both enabled, which obviously wasn't going to work 😅 Fortunately I'm able to work around this by [disabling the default features](https://doc.rust-lang.org/cargo/reference/features.html#the-default-feature) in my dependencies like so:

```toml
dnsclient = { version = "0.1.17", default-features = false, features = ["async-tokio"] }
```

Would you be open to removing the "async" feature from the defaults so folks don't need to disable the defaults when using tokio? I'm happy to open a PR if so.

Thanks!

**Comment by jedisct1** [comment]
I'm not sure that removing the default backend is a good idea. It would break backwards compatibility, and mean that by default, the library is not usable at all.

Maybe what we can do is document this, and possibly print a compile error if multiple, incompatible backends are enabled (not sure if Rust has something like Zig's `@compileError` in order to achieve that).

**Comment by brahmlower** [comment]
> It would break backwards compatibility

Ah yeah that makes sense. Wasn't just sure if that was in the cards since the version is still unstable.

I see that there is a [`std::compile_error` macro](https://doc.rust-lang.org/std/macro.compile_error.html) for custom compiler errors. I will throw together a PR this evening with a note in the docs and an added compiler error message 👍

**Comment by brahmlower** [comment]
Oh! I just noticed you pushed the compiler warning change for this last night. Thank you, much appreciated! 🙏
